name: CI

on:
  workflow_dispatch:
    inputs:
      refToBuild:
        description: 'Branch, tag or commit SHA1 to build'
        required: true
        type: string

  push:
    branches: [master, experimental]
    paths-ignore:
      # Case-sensitive paths to ignore on push events
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - 'MergeDbg.cmd'
      - 'TestCI.cmd'
      - '.github/codeql/codeql-config.yml'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/codespell.yml'
      - '.github/workflows/hash.yml'
      - '.github/workflows/lupdate.yml'
      - '.github/workflows/stale.yml'
      - '.github/workflows/test.yml'
      - '.github/workflows/winget.yml'
      - '.github/FUNDING.yml'
      - '.github/dependabot.yml'
      - 'Sandboxie/msgs/report/*.txt'
      - '**/*.md'
      - '**/*.html'
      - '**/*.png'
      - '**/*.bmp'
      - '**/LICENSE*'
      - '**/license*'
      - '**/README*'
      - '**/ReadMe*'
      - '**/INSTALL*'
      - '**/AUTHORS'
      - '**/COPYING'
  pull_request:
    branches: [master, experimental]
    paths-ignore:
      # Case-sensitive paths to ignore on pull events
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - 'MergeDbg.cmd'
      - 'TestCI.cmd'
      - '.github/codeql/codeql-config.yml'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/codespell.yml'
      - '.github/workflows/hash.yml'
      - '.github/workflows/lupdate.yml'
      - '.github/workflows/stale.yml'
      - '.github/workflows/test.yml'
      - '.github/workflows/winget.yml'
      - '.github/FUNDING.yml'
      - '.github/dependabot.yml'
      - 'Sandboxie/msgs/report/*.txt'
      - '**/*.md'
      - '**/*.html'
      - '**/*.png'
      - '**/*.bmp'
      - '**/LICENSE*'
      - '**/license*'
      - '**/README*'
      - '**/ReadMe*'
      - '**/INSTALL*'
      - '**/AUTHORS'
      - '**/COPYING'

env:
  forbuildVariables: use Installer\buildVariables.cmd file
  #qt_version: 5.15.16
  #qt6_version: 6.6.3
  #openssl_version: 3.4.0
  #ghSsl_user: xanasoft
  #ghSsl_repo: openssl-builds
  #ghQt6Win7_user: DavidXanatos
  #ghQt6Win7_repo: qtbase
  #ghQtBuilds_user: xanasoft
  #ghQtBuilds_repo: qt-builds
  #ghQtBuilds_hash_x86: 502e9a36a52918af4e116cd74c16c6c260d029087aaeee3775ab0e5d3f6a2705
  #ghQtBuilds_hash_x64: 673c288feeabd11ec66f9f454d49cde3945cbd3e3f71283b7a6c4df0893b19f2

jobs:
          
  Build_x64_Qt6:
  # if: ${{false}}
    runs-on: windows-2022
    timeout-minutes: 45
  # continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ inputs.refToBuild }}

      - name: Load Variables from buildVariables.cmd
        shell: cmd
        run: |
          @echo on
          call "${{ github.workspace }}\Installer\buildVariables.cmd" build_qt6
          echo qt6_version=%qt6_version% >> %GITHUB_ENV%
          echo qt_version=%qt6_version% >> %GITHUB_ENV%

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2

    #
    # Compile Sandboxie Core
    #

      - name: Build Sandboxie x86 (DLLs & svc)
        run: msbuild /t:build Sandboxie\SandboxDll.sln /p:Configuration="SbieRelease" /p:Platform=Win32 -maxcpucount:8

      - name: Build Sandboxie x64 (all)
        run: msbuild /t:build Sandboxie\Sandbox.sln /p:Configuration="SbieRelease" /p:Platform=x64 -maxcpucount:8
        
      - name: Build Sandboxie x64 (drv)
        run: msbuild /t:build Sandboxie\SandboxDrv.sln /p:Configuration="SbieRelease" /p:Platform=x64 -maxcpucount:8

    #
    # Merge everything together
    #

      - name: Merging Build
        run: Installer\copy_build.cmd x64 build_qt6

      - name: Collect installer assets
        run: Installer\get_assets.cmd

      - name: Upload installer assets
        #if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Assets
          path: |
            Installer/Assets/*
          retention-days: 60

      - name: Upload Sandboxie x64
        #if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Sandboxie_x64
          path: |
            Installer/SbiePlus_x64/*
          retention-days: 60




  Build_ARM64_Qt6:
  # if: ${{false}}
    runs-on: windows-2022
    timeout-minutes: 45
  # continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ inputs.refToBuild }}

      - name: Load Variables from buildVariables.cmd
        shell: cmd
        run: |
          @echo on
          call "${{ github.workspace }}\Installer\buildVariables.cmd" build_qt6
          echo qt6_version=%qt6_version% >> %GITHUB_ENV%

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2

    #
    # Compile Sandboxie Core
    #

      - name: Build Sandboxie x86 (DLLs & svc)
        run: msbuild /t:build Sandboxie\SandboxDll.sln /p:Configuration="SbieRelease" /p:Platform=Win32 -maxcpucount:8

      - name: Build Sandboxie ARM64 (all)
        run: msbuild /t:build Sandboxie\Sandbox.sln /p:Configuration="SbieRelease" /p:Platform=ARM64 -maxcpucount:8

      - name: Build Sandboxie ARM64EC (DLL)
        run: msbuild /t:build Sandboxie\SandboxDll.sln /p:Configuration="SbieRelease" /p:Platform=ARM64EC -maxcpucount:8

      - name: Build Sandboxie ARM64 (drv)
        run: msbuild /t:build Sandboxie\SandboxDrv.sln /p:Configuration="SbieRelease" /p:Platform=ARM64 -maxcpucount:8

    #
    # Merge everything together
    #

      - name: Merging Build
        run: Installer\copy_build.cmd ARM64 build_qt6

      - name: Upload Sandboxie ARM64
        #if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Sandboxie_ARM64
          path: |
            Installer/SbiePlus_a64/*
          retention-days: 60
